### ISSUE TITLE
Android  device run error

### ISSUE THREAD

**Issue by davipromob** [bestmob/senchaTestApp#2]
2021-02-06 18:04:34.756 29515-29515/com.buildshop I/chromium: [INFO:CONSOLE(151)] "Failed because: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference", source: file:///android_asset/www/index.html (151)
2021-02-06 18:04:39.450 29515-29590/com.buildshop E/PluginManager: Uncaught exception from plugin
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:584)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
        at org.apache.cordova.camera.CameraLauncher.takePicture(CameraLauncher.java:296)
        at org.apache.cordova.camera.CameraLauncher.callTakePicture(CameraLauncher.java:274)
        at org.apache.cordova.camera.CameraLauncher.execute(CameraLauncher.java:192)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:329)
        at android.os.Looper.loop(Looper.java:142)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2021-02-06 18:04:39.453 29515-29515/com.buildshop I/chromium: [INFO:CONSOLE(181)] "Failed because: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference", source: file:///android_asset/www/index.html (181)

**Comment by davipromob** [comment]
2021-02-06 18:13:08.050 29515-29584/com.buildshop E/chromium: [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
