### ISSUE TITLE
Android Crash log

### ISSUE THREAD

**Issue by davipromob** [bestmob/senchaTestApp#4]
--------- beginning of crash
2021-02-08 04:50:42.245 3516-3516/com.buildshop E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.buildshop, PID: 3516
    java.lang.RuntimeException: Unable to get provider com.transistorsoft.locationmanager.util.LogFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.locationmanager.util.LogFileProvider" on path: DexPathList[[zip file "/data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/base.apk"],nativeLibraryDirectories=[/data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/lib/arm64, /data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6581)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.transistorsoft.locationmanager.util.LogFileProvider" on path: DexPathList[[zip file "/data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/base.apk"],nativeLibraryDirectories=[/data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/lib/arm64, /data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6566)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 12 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/base.apk"],nativeLibraryDirectories=[/data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/lib/arm64, /data/app/com.buildshop-RMfS9kX8kGdyexTdxtvVug==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more

**Comment by davipromob** [comment]
> Task :app:checkDebugDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class android.support.design.widget.CoordinatorLayout found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$1 found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$Behavior found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$DefaultBehavior found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$DispatchChangeEvent found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$HierarchyChangeListener found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$LayoutParams found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$OnPreDrawListener found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$SavedState found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$SavedState$1 found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.design.widget.CoordinatorLayout$ViewElevationComparator found in modules design-25.0.0-runtime.jar (com.android.support:design:25.0.0) and support-core-ui-27.1.1-runtime.jar (com.android.support:support-core-ui:27.1.1)
  Duplicate class android.support.v13.view.DragAndDropPermissionsCompat found in modules support-compat-27.1.1-runtime.jar (com.android.support:support-compat:27.1.1) and support-v13-24.1.1-runtime.jar (com.android.support:support-v13:24.1.1)
  Duplicate class android.support.v13.view.DragStartHelper found in modules support-compat-27.1.1-runtime.jar (com.android.support:support-compat:27.1.1) and support-v13-24.1.1-runtime.jar (com.android.support:support-v13:24.1.1)
  Duplicate class android.support.v13.view.DragStartHelper$1 found in modules support-compat-27.1.1-runtime.jar (com.android.support:support-compat:27.1.1) and support-v13-24.1.1-runtime.jar (com.android.support:support-v13:24.1.1)
  Duplicate class android.support.v13.view.DragStartHelper$2 found in modules support-compat-27.1.1-runtime.jar (com.android.support:support-compat:27.1.1) and support-v13-24.1.1-runtime.jar (com.android.support:support-v13:24.1.1)
  Duplicate class android.support.v13.view.DragStartHelper$OnDragStartListener found in modules support-compat-27.1.1-runtime.jar (com.android.support:support-compat:27.1.1) and support-v13-24.1.1-runtime.jar (com.android.support:support-v13:24.1.1)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
21 actionable tasks: 21 executed
Command failed with exit code 1: F:\Cordova\sencha\senchaTestApp\platforms\android\gradlew cdvBuildDebug -b F:\Cordova\sencha\senchaTestApp\platforms\android\build.gradle
